/* https://school.programmers.co.kr/learn/courses/30/lessons/131530*/

SELECT 10000 * (PRICE DIV 10000) AS PRICE_GROUP, COUNT(1) AS PRODUCTS
-- SELECT TRUNCATE(PRICE, -4) AS PRICE_GROUP, COUNT(1) AS PRODUCTS
FROM PRODUCT
GROUP BY PRICE_GROUP
ORDER BY PRICE_GROUP
;