/* https://school.programmers.co.kr/learn/courses/30/lessons/293257 */

SELECT COUNT(1) AS FISH_COUNT, NI.FISH_NAME
FROM FISH_INFO I
    JOIN FISH_NAME_INFO NI
    ON I.FISH_TYPE = NI.FISH_TYPE
GROUP BY NI.FISH_NAME
ORDER BY COUNT(1) DESC
;