/* https://school.programmers.co.kr/learn/courses/30/lessons/132202 */

SELECT MCDP_CD AS '진료과코드', COUNT(APNT_NO) AS '5월예약건수'
FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = '2022' AND MONTH(APNT_YMD) = '05'
     -- AND APNT_CNCL_YN = 'N' AND APNT_CNCL_YMD IS NULL
GROUP BY MCDP_CD
ORDER BY COUNT(APNT_NO), MCDP_CD
;