/* https://school.programmers.co.kr/learn/courses/30/lessons/59042 */

SELECT OUTS.ANIMAL_ID
    , OUTS.NAME
FROM ANIMAL_OUTS OUTS
    LEFT OUTER JOIN ANIMAL_INS INS
        ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE INS.ANIMAL_ID IS NULL
ORDER BY OUTS.ANIMAL_ID
;